SELECT * FROM EMP;

SELECT ename FROM emp;

SELECT ENAME, JOB FROM EMP;

SELECT DISTINCT JOB FROM EMP;

SELECT DISTINCT ENAME, JOB FROM EMP;

SELECT JOB AS A FROM EMP;

SELECT * FROM DEPT;

SELECT * FROM DEPT WHERE DEPTNO = 30;

SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

SELECT * FROM EMP WHERE DEPTNO = 30 OR JOB = 'CLERK';

SELECT * FROM EMP;

SELECT * FROM EMP WHERE SAL * 12 = 36000;

SELECT * FROM EMP;

SELECT * FROM EMP WHERE SAL != 3000;

SELECT * FROM EMP WHERE SAL <> 3000;

SELECT * FROM EMP WHERE NOT SAL = 3000;

SELECT * FROM EMP;

SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN' OR JOB = 'CLERK';

SELECT * FROM EMP;
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
SELECT * FROM EMP WHERE SAL >=2000 AND SAL <=3000;
SELECT * FROM EMP WHERE NOT SAL BETWEEN 2000 AND 3000;
SELECT ENAME, JOB FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP;
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%AM%';

SELECT ENAME, JOB, HIREDATE FROM EMP WHERE COMM IS NULL;
SELECT ENAME, JOB, SAL FROM EMP WHERE MGR IS NOT NULL;