SELECT * FROM EMP;

SELECT * FROM EMP WHERE SAL > NULL AND COMM IS NULL;

SELECT * FROM EMP WHERE SAL > NULL OR COMM IS NULL;

SELECT EMPNO, ENAME, SAL, DEPTNO 
FROM EMP 
WHERE DEPTNO = 10 
UNION SELECT EMPNO, ENAME, SAL, DEPTNO 
FROM EMP 
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT * FROM EMP;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME) FROM EMP;

SELECT * FROM EMP WHERE UPPER(ENAME) = UPPER('scott');

SELECT * FROM EMP WHERE UPPER(ENAME) LIKE UPPER('%scott%');

SELECT * FROM EMP;
SELECT ENAME, LENGTH(ENAME) AS ENAMELENGTH FROM EMP;

SELECT * FROM EMP;
SELECT ENAME, LENGTH(ENAME) AS ENAMELENGTH FROM EMP WHERE LENGTH(ENAME) >= 5;

SELECT * FROM EMP;
SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5) FROM EMP;

SELECT * FROM EMP;
SELECT * FROM EMP WHERE INSTR(ENAME, 'S') > 0;
SELECT * FROM EMP WHERE INSTR(ENAME, 'S') > 2;

SELECT '010-1234-5678' AS REPLACE_BEFORE, REPLACE('010-1234-5678', '-', '') AS REPLACE_1 FROM DUAL;
SELECT 'Oracle', LPAD('Oracle', 10, '#') AS LPAD_1, RPAD('Oracle', 10, '*') AS RPAD_1 FROM DUAL;

SELECT * FROM EMP;
SELECT 
CONCAT(EMPNO, ENAME), CONCAT(EMPNO, CONCAT(':', ENAME)) 
FROM EMP 
WHERE ENAME = 'SCOTT';

SELECT ROUND(1234.5678) AS ROUND,
ROUND(1234.5678,0) AS ROUND_0,
ROUND(1234.5678,1) AS ROUND_1,
ROUND(1234.5678,2) AS ROUND_2
FROM DUAL;

SELECT TRUNC(1234.5678) AS TRUNC,
TRUNC(1234.5678,0) AS TRUNC_0,
TRUNC(1234.5678,1) AS TRUNC_1,
TRUNC(1234.5678,2) AS TRUNC_2
FROM DUAL;

SELECT CEIL(3.14),
FLOOR(3.14),
CEIL(-3.14),
FLOOR(-3.14)
FROM DUAL;

SELECT SYSDATE AS NOW,
SYSDATE-1 AS YESTERDAY,
SYSDATE+1 AS TOMORROW
FROM DUAL;

SELECT SYSDATE,
ADD_MONTHS(SYSDATE, 3)
FROM DUAL;

SELECT * FROM EMP;

SELECT EMPNO, ENAME, HIREDATE,
ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
FROM EMP;

SELECT * FROM EMP;
SELECT EMPNO, ENAME, HIREDATE, SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE,384) > SYSDATE;

SELECT SYSDATE,
TO_CHAR(SYSDATE, 'HH24:MI:SS')AS HH24MISS,
TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HHMISS_AM,
TO_CHAR(SYSDATE, 'HH:MI:SS P.M.') AS HHMISS_PN
FROM DUAL;

SELECT 
TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999') 
FROM DUAL;
SELECT 
TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999') AS SUB_RESULT,
TO_NUMBER('1,300', '999,999') + TO_NUMBER('1,500', '999,999') AS ADD_RESULT
FROM DUAL;

SELECT 
TO_DATE('2018-07-14', 'YYYY-MM-DD') AS TODATE1,
TO_DATE('20180714', 'YYYY-MM-DD') AS TODATE2
FROM DUAL;

SELECT * FROM EMP;
SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1981/06/01', 'YYYY/MM/DD');

SELECT * FROM EMP;
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM, NVL(COMM,0), SAL+NVL(COMM,0)
FROM EMP;

SELECT * FROM EMP;
SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X'), 
        NVL2(COMM, SAL*12+COMM, SAL*12) AS ANNSAL
FROM EMP;

SELECT * FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
CASE JOB
WHEN 'MANAGER' THEN SAL * 1.1
WHEN 'SALESMAN' THEN SAL *1.05
WHEN 'ANALYST' THEN SAL
ELSE SAL*1.03
END AS UPSAL
FROM EMP;

SELECT * FROM EMP;

SELECT EMPNO, ENAME, COMM,
CASE
WHEN COMM IS NULL THEN '해당사항 없음'
WHEN COMM = 0 THEN '수당없음'
WHEN COMM > 0 THEN '수당: ' || COMM
END AS COMM_TEXT
FROM EMP;

SELECT * FROM EMP;

SELECT COUNT(*) FROM EMP;
SELECT COUNT(*) FROM EMP
WHERE DEPTNO = 30;

SELECT COUNT(COMM)
FROM EMP;
SELECT COUNT(COMM) FROM EMP
WHERE COMM IS NOT NULL;

SELECT * FROM EMP;

SELECT MAX(SAL)
FROM EMP
WHERE DEPTNO = 10;

SELECT MAX(HIREDATE)
FROM EMP
WHERE DEPTNO = 20;

SELECT MIN(SAL)
FROM EMP
WHERE DEPTNO = 30;

SELECT ROUND(AVG(SAL),2), '10' AS DEPTNO
FROM EMP
WHERE DEPTNO = 10;

UNION ALL
SELECT ROUND(AVG(SAL),2), '20' AS DEPTNO
FROM EMP
WHERE DEPTNO = 20;

UNION ALL
SELECT ROUND(AVG(SAL),2), '30' AS DEPTNO
FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP;

SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB , AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE SAL <=3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;