show user

CREATE TABLE TEST_MEMBER (
    MEM_NO    NUMBER(4) PRIMARY KEY,    -- 회원번호 (기본키)
    MEM_NAME  VARCHAR2(20) NOT NULL,    -- 이름
    JOB       VARCHAR2(20),             -- 직책
    HIREDATE  DATE,                    -- 가입일
    SAL       NUMBER(10),               -- 급여
    COMM      NUMBER(10),               -- 추가수당
    DEPTNO    NUMBER(2)                 -- 부서번호
);


INSERT INTO TEST_MEMBER VALUES (1001, 'KANG', 'MANAGER', '2024-01-01', 5000, NULL, 10);
INSERT INTO TEST_MEMBER VALUES (1002, 'KIM', 'ANALYST', '2024-02-15', 3000, 500, 20);
INSERT INTO TEST_MEMBER VALUES (1003, 'LEE', 'CLERK', '2024-03-10', 1500, NULL, 20);
INSERT INTO TEST_MEMBER VALUES (1004, 'PARK', 'SALESMAN', '2024-03-20', 2500, 1000, 30);
INSERT INTO TEST_MEMBER VALUES (1005, 'CHOI', 'CLERK', '2024-04-01', 1200, NULL, 10);

COMMIT; -- 변경사항 저장

SELECT * FROM TEST_MEMBER;

SELECT MEM_NAME, JOB FROM TEST_MEMBER;

SELECT MEM_NAME, JOB, SAL FROM TEST_MEMBER;

SELECT * FROM TEST_MEMBER WHERE DEPTNO IN (10, 20, 30);

SELECT JOB AS 사원직책 FROM TEST_MEMBER WHERE JOB NOT IN ('MANAGER', 'SALESMAN'); 

SELECT JOB AS 사원직책, SAL AS 사원급여 FROM TEST_MEMBER WHERE JOB = 'CLERK' AND SAL >= 1200;

SELECT DEPTNO AS 부서번호 , JOB AS 사원직책 FROM TEST_MEMBER WHERE DEPTNO = 10 OR JOB = 'ANALYST';



